Proper IFS setting, style changes, and preserve history order

diff --git a/fzf_recent b/fzf_recent
--- a/fzf_recent
+++ b/fzf_recent
@@ -3,40 +3,39 @@
 # environment variable, something like "xterm -e", so applications may be
 # launched in your terminal of choice.
 
-# This script doesn't execute commands, instead they're just printed to stdout.
-# Execute the stdout in whatever fashion you want.
+# This script doesn't execute selected commands, they are instead printed to
+# stdout. Execute the stdout in whatever fashion you want.
 
 # This script uses custom keybinds for ease of use in application selection:
-#  tab: Replace query string with the current selection, like Bash tab complete
+#  tab: Replace query string with the current selection, i.e. tab completion
 #  enter: print-query, i.e. just print query string regardless of the selection
 
-err() { printf '%s\n' "ERROR: $1" >&2; exit 1; }
+set -e
 
-# Lists all of the executables on $PATH. Slow and ugly, but portable!
-commands() {
-	IFS_="$IFS"; IFS=:;
-	for path in $PATH; do
+err() { printf '%s\n' "ERROR: $1" >&2; exit 1; }
+tac() { sed '1!G;h;$!d' "$@"; }
+list_choices() { awk '!seen[$0]++' "$cache_dir/recent" "$cache_dir/all"; }
+list_path() {(
+	# List all executables on $PATH
+	IFS=:; for path in $PATH; do
 		find "$path" -maxdepth 1 -executable \
 			-exec basename {} \; 2> /dev/null
 	done
-	IFS="$IFS_"
-}
+)}
 
 [ ! "$TERMCMD" ] && err '$TERMCMD must be set, i.e. "xterm -e"'
 
-# Find the cache/config directories and ensure they exist
 cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/fzf-recent"
 config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/fzf-recent"
 mkdir -p "$cache_dir" "$config_dir"
 
 # Ensure all of the config/cache files exist
-[ ! -f "$cache_dir/all" ] && commands > "$cache_dir/all"
-touch "$cache_dir/recent" "$config_dir/background" "$config_dir/terminal"
+[ ! -f "$cache_dir/all" ] && list_path > "$cache_dir/all"
+: >> "$cache_dir/recent" >> "$config_dir/background" >> "$config_dir/terminal"
 
 # Filter out duplicates and pass commands to fzf (+ custom keybinds)
 opts='--bind=enter:print-query,tab:replace-query+top'
-selection=$(awk '!seen[$0]++' "$cache_dir/recent" "$cache_dir/all" |
-	fzf $opts --history="$cache_dir/recent")
+selection="$(list_choices | fzf $opts --history="$cache_dir/recent")"
 
 # Ensure the selection exists
 [ ! "$selection" ] && err 'Nothing was selected!'
@@ -49,11 +48,11 @@ elif grep -Fxq "$selection" "$config_dir/terminal"; then
 	printf '%s\n' "$TERMCMD $selection"
 else
 	msg="Run $selection in the background or in the terminal?"
-	choice=$(printf '%s\n%s' 'background' 'terminal' | fzf --header="$msg")
+	context=$(printf '%s\n%s' 'background' 'terminal' | fzf --header="$msg")
 	
-	if [ "$choice" = 'background' ]; then
+	if   [ "$context" = 'background' ]; then
 		printf '%s\n' "$selection" | tee -a "$config_dir/background"
-	elif [ "$choice" = 'terminal' ]; then
+	elif [ "$context" = 'terminal' ]; then
 		printf '%s\n' "$selection" >> "$config_dir/terminal"
 		printf '%s\n' "$TERMCMD $selection"
 	else
@@ -61,8 +60,8 @@ else
 	fi
 fi
 
-# Remove duplicates from history
+# Remove duplicates from history while preserving order
 tmp="$(mktemp)"
-awk '!seen[$0]++' "$cache_dir/recent" > "$tmp"
+tac "$cache_dir/recent" | awk '!seen[$0]++' | tac > "$tmp"
 mv "$tmp" "$cache_dir/recent"
 
